{
 "title": "Mysql-Audit审查",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "database",
    "label": "数据库实例",
    "query": "{\"find\":\"terms\",\"field\":\"tag_key.keyword\"}"
   },
   {
    "name": "cmd",
    "label": "操作分类",
    "query": "{\"find\":\"terms\",\"query\":\"tag_key:$database\",\"field\":\"cmd.keyword\"}"
   },
   { "name": "filter", "label": "模糊过滤" }
  ]
 },
 "panels": [
  {
   "title": "数据库：$database 总操作数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tag_key:$database",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "数据库：$database 操作分类统计",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "cmd.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "15" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag_key:$database",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$database  客户端 IP 操作 TOP 10",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "ip.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag_key:$database",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "每小时 $cmd 操作总数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag_key:$database AND cmd:$cmd",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "数据库：$database  操作分类：$cmd",
   "type": "table-old",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "hide": false,
       "id": "1",
       "meta": {},
       "settings": { "size": "200" },
       "type": "raw_document"
      }
     ],
     "query": "tag_key:$database AND cmd:$cmd AND $filter*",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}